apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  # disable default behavior:
  #   default behavior: `ignoreDifferences` customizations -> apply | `ignoreResourceUpdates`
  resource.compareoptions: |
    ignoreDifferencesOnResourceUpdates: false