apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  resource.customizations.ignoreResourceUpdates.batch_Job: |
    jsonPointers:
      - /status
  resource.customizations.ignoreResourceUpdates.Pod: |
    jsonPointers:
      - /status