apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  # https://external-secrets.io/main/api/externalsecret/
  resource.customizations.ignoreResourceUpdates.external-secrets.io_ExternalSecret:
    |
    jsonPointers:
    - /status/refreshTime
    # JQ equivalent of the above:
    # jqPathExpressions:
    # - .status.refreshTime