apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  configManagementPlugins: |
    - name: pluginName
      
      # Optional command to initialize application source directory
      init:                          
        command: ["sample command"]
        args: ["sample args"]
      
      # Command to generate Kubernetes Objects in either YAML or JSON
      generate:                      
        command: ["sample command"]
        args: ["sample args"]
      
      # by default, false
      lockRepo: true                 
