# goal
#   custom image for the sidecar
FROM ubuntu:22.04

WORKDIR /home/argocd/cmp-server/config/
# add DIRECTLY the plugin configuration file | custom image
COPY configManagementPlugin.yaml ./plugin.yaml