apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/argoproj/argo-cd/manifests/cluster-install

patches:
  - target:
      kind: Deployment
      name: argocd-repo-server
    path: repo-server-patch.yaml