apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  # policy.csv
  #   == user-defined RBAC policies (`p`) + role definitions (`g`)
  #     1. user-defined RBAC policies
  #         p, subject, resource, action, object, effect
  #     2. role definitions
  #         g, subject, role
  policy.csv: |
    # group 'my-org:team-alpha' members can sync apps | 'my-project'
    p, my-org:team-alpha, applications, sync, my-project/*, allow
    # group 'my-org:team-beta' is granted -- with -- 'role:admin' rights
    g, my-org:team-beta, role:admin

  # 'policy.<any string>.csv'
  #   format
  # allows
  #   adding ADDITIONAL entries / are appended -- to -- values | policy.csv
  policy.overlay.csv: |
    p, role:tester, applications, *, */*, allow
    p, role:tester, projects, *, *, allow
    g, my-org:team-qa, role:tester

  # policy.default
  #   == default role name / Argo CD will falls back to | authenticated user has NO specific role
  #   can NOT be blocked -- by a -- `deny` rule
  #     == if a user / inherits the default policy & try to set a deny rule | the user -> skipped the deny policy rule
  #   OPTIONAL
  #     if it's omitted OR empty -> users
  #       STILL can login
  #       NO see apps, projects, etc...
  #   recommendations
  #     create a NEW `role:authenticated` / minimum set of permissions
  policy.default: role:readonly

  # scopes controls which OIDC scopes to examine during rbac enforcement (in addition to `sub` scope).
  # If omitted, defaults to: '[groups]'. The scope value can be a string, or a list of strings.
  scopes: '[cognito:groups, email]'

  # matchMode configures the matchers function for casbin.
  # There are two options for this, 'glob' for glob matcher or 'regex' for regex matcher. If omitted or mis-configured,
  # will be set to 'glob' as default.
  policy.matchMode: 'glob'

