apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-project
  namespace: argocd
  # Finalizer
  #   allow
  #     TILL project is NOT reference by any application, project is NOT deleted
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: Example Project

  # ALLOWED source repos / AppProject's ArgoCD Applications source of truth could come from
  sourceRepos:
  # ALL are ALLOWED
  - '*'

  # Kubernetes cluster & namespace | Applications can be deployed
  # ways to identify the destination clusters
  #   1. -- by -- 'server'
  #   2. -- by -- 'name'
  #   3. -- by -- 'name' + 'server'
  destinations:
  - namespace: guestbook
    server: https://kubernetes.default.svc
    name: in-cluster
  # Destinations also allow wildcard globbing
  - namespace: guestbook-*
    server: https://kubernetes.default.svc
    name: in-cluster

  # cluster-scoped resources / ALLOWED from being created
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
    # Name
    #   OPTIONAL
    #     if it's specified -> ONLY resources / matching name are ALLOWED
    # Globs in Go's filepath.Match syntax are supported. Example: "team1-*".
    name: ''

  # cluster-scoped resources / DENIED from being created
  clusterResourceBlacklist:
    - group: ''
      kind: Namespace
      # Name
      #   OPTIONAL
      #     if it's specified -> ONLY resources / matching name are DENIED
      name: 'kube-*'

  # cluster-scoped resources / DENIED from being created
  #   == REST can be created
  namespaceResourceBlacklist:
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
  - group: ''
    kind: NetworkPolicy

  # cluster-scoped resources / ALLOWED from being created
  #   == REST can NOT be created
  namespaceResourceWhitelist:
  - group: 'apps'
    kind: Deployment
  - group: 'apps'
    kind: StatefulSet

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: false

  #
  roles:
  # role / provides
  #     read-only access | ALL project's applications
  - name: read-only
    description: Read-only privileges to my-project
    policies:
    - p, proj:my-project:read-only, applications, get, my-project/*, allow
    # groups
    #   ==  OIDC group claims / bound -- to -- this role
    groups:
    - my-oidc-group

  # role / provides
  #     sync privileges | "guestbook-dev" application
  - name: ci-role
    description: Sync privileges for guestbook-dev
    # policies
    #   == Casbin formatted strings /
    #     define project's RBAC roles
    policies:
    - p, proj:my-project:ci-role, applications, sync, my-project/guestbook-dev, allow

    # JWT tokens
    #   == generated JWT tokens / bound -- to -- this role
    #   ONLY can be generated -- by the -- API server
    #   are NOT persisted | Argo CD
    #   if you want to remove the entry | this list -> you can revoke prematurely
    jwtTokens:
    - iat: 1535390316

  # Sync windows restrict when Applications may be synced. https://argo-cd.readthedocs.io/en/stable/user-guide/sync_windows/
  syncWindows:
  - kind: allow
    schedule: '10 1 * * *'
    duration: 1h
    applications:
      - '*-prod'
    manualSync: true
  - kind: deny
    schedule: '0 22 * * *'
    duration: 1h
    namespaces:
      - default
  - kind: allow
    schedule: '0 23 * * *'
    duration: 1h
    clusters:
      - in-cluster
      - cluster1

  # By default, apps may sync to any cluster specified under the `destinations` field, even if they are not
  # scoped to this project. Set the following field to `true` to restrict apps in this cluster to only clusters
  # scoped to this project.
  permitOnlyProjectScopedClusters: false

  # When using Applications-in-any-namespace, this field determines which namespaces this AppProject permits
  # Applications to reside in. Details: https://argo-cd.readthedocs.io/en/stable/operator-manual/app-any-namespace/
  sourceNamespaces:
  - "argocd-apps-*"
