apiVersion: v1
kind: Secret
metadata:
  name: private-repo-https-usernameandpassword
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
# stringData
#   == raw
stringData:
  # url
  # 1. ❌NOT valid | Github❌
  #url: "https://github.com/dancer1325/argocd-example-apps-private.git"
  # 2. use: GitLab self-hosted OR Bitbucket Server on-premise OR Azure DevOps
  url: "TODO: "
  #username: "<USERNAME_GIT_PROVIDER_DEPENDANT>"
  username: "your-username"
  password: "your-password-or-token"
  type: "git"
# stringData
#   == bas64
#data:
---
apiVersion: v1
kind: Secret
metadata:
  name: private-repo-https-accesstoken
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
# stringData
#   == raw
stringData:
  #username: "<USERNAME_GIT_PROVIDER_DEPENDANT>"
  url: "https://github.com/dancer1325/argocd-example-apps-private.git"
  username: "your-username"
  password: "<GITHUB_TOKEN>"
  type: "git"
---
apiVersion: v1
kind: Secret
metadata:
  name: private-repo-https-tlsclientcertificates
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  #username: "<USERNAME_GIT_PROVIDER_DEPENDANT>"
  url: "TODO:"
  tlsClientCertData: "TLS_CLIENT_CERT_DATA_PEMFORMAT"
  tlsClientCertKey: "TLS_CLIENT_CERT_KEY_PEMFORMAT"
  type: "git"
---
apiVersion: v1
kind: Secret
metadata:
  name: private-repo-ssh
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: "TODO:"
  sshPrivateKey: "SSH_PRIVATE_KEY"
  type: "git"