apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multiple-sources-app
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  # source
  #   ignored because it's ALSO specified sources
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    path: guestbook
  sources:
    - repoURL: https://github.com/dancer1325/argocd-example-apps.git
      path: guestbook
    - repoURL: https://github.com/dancer1325/argocd-example-apps.git
      path: helm-guestbook
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multiple-sources-which-produce-sameresource-app
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  sources:
    - repoURL: https://github.com/argoproj/argocd-example-apps.git
      path: guestbook
    # NEXT source
    #   produce SAME k8s resource
    - repoURL: https://github.com/dancer1325/argocd-example-apps.git
      path: guestbook