# valueFiles, | Argo CD v2.6+, git repository | values files (can be) != git repository | Helm chart
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook-valuesfiles-differentrepo
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/dancer1325/argocd-example-apps
      path: helm-guestbook
      helm:
        valueFiles:
          - $values/docs/user-guide/examples/multipleSources/values-production.yaml  # $values = ANOTHER repo's root
    - repoURL: https://github.com/dancer1325/argo-cd
      targetRevision: HEAD
      # ref
      #   creates the $values variable
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: helm-guestbook-valuesfiles-differentrepo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true