apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  sources:
    - repoURL: 'https://prometheus-community.github.io/helm-charts'
      chart: prometheus
      targetRevision: 15.7.1
      helm:
        valueFiles:
          - $values/charts/prometheus/values.yaml
          # $values
    # source -- with -- the values
    - repoURL: 'https://git.example.com/org/value-files.git'
      targetRevision: dev
      ref: values   # map -- to the -- variable `$values`   -> resolve to "value-files" repository | root