apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons-exclude-reverseorder-notmatter
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/dancer1325/argo-cd.git
      revision: HEAD
      directories:
      # reverse order | specify path
      - exclude: true
        path: applicationset/examples/git-generator-directory/excludes/cluster-addons/exclude-helm-guestbook
      - path: applicationset/examples/git-generator-directory/excludes/cluster-addons/*
  template:
    metadata:
      name: '{{.path.basename}}-cluster-addons-exclude-reverseorder-notmatter'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/dancer1325/argo-cd.git
        targetRevision: HEAD
        path: '{{.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
