apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-kind2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://172.18.0.3:6443
    #server: "https://<docker inspect kind2-control-plane --format '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}')>:6443"s
    namespace: default
