# 1. -- for a -- Helm repository
apiVersion: v1
kind: Secret
metadata:
  name: argo-helm
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: argo
  url: https://argoproj.github.io/argo-helm
  type: helm
  username: my-username
  password: my-password
  tlsClientCertData: ...
  tlsClientCertKey: ...

---
# 2, -- for a -- public OCI helm chart
apiVersion: v1
kind: Secret
metadata:
  name: oci-helm-chart
  namespace: oci-helm-chart
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: oci-helm-chart
  url: myregistry.example.com
  type: helm
  enableOCI: "true"       # OCI helm chart specific