apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: git-directory-reque-afterseconds
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/dancer1325/argo-cd.git
      revision: HEAD
      directories:
      - path: applicationset/examples/git-generator-directory/cluster-addons/*
      requeueAfterSeconds: 45
  template:
    metadata:
      name: '{{.path.basename}}-reque-afterseconds'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/dancer1325/argo-cd.git
        targetRevision: HEAD
        path: '{{.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
