apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hello-world
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - stage: test
        server: https://k8s-test.example.com
      - stage: preprod
        server: https://k8s-preprod.example.com
      - stage: prod
        server: https://k8s-prod.example.com
  template:
    metadata:
      name: hello-world-{{stage}}
    spec:
      project: default
      source:
        repoURL: https://github.com/dancer1325/argo-cd-hello-world-config
        targetRevision: HEAD
        path: helm
        helm:
          valueFiles:
          - values.{{stage}}.yaml
      destination:
        server: '{{server}}'
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
