apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  # create 1 Argo CD application / EACH generator's element
  generators:
    - list:
        elements:
          - env: dev
          - env: staging
  # generated parameters are substituted | spec.template
  template:
    metadata:
      name: 'guestbook-{{.env}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/dancer1325/argocd-example-apps
        targetRevision: HEAD
        path: guestbook
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.env}}'

# --- Generated Applications ---
#
# Application 1 (env: dev):
#
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: guestbook-dev
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/dancer1325/argocd-example-apps
#     targetRevision: HEAD
#     path: guestbook
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: dev
#
# Application 2 (env: staging):
#
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: guestbook-staging
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/dancer1325/argocd-example-apps
#     targetRevision: HEAD
#     path: guestbook
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: staging