apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  # create 1 Argo CD application / EACH generator's element
  generators:
    - list:
        elements:
          - cluster: docker-desktop
            url: https://kubernetes.default.svc
          # TODO: add minikube after running: argocd cluster add minikube --server localhost:8080 --insecure
          # - cluster: minikube
          #   url: https://192.168.49.2:8443
  template:
    metadata:
      name: '{{.cluster}}-guestbook'    # {{.cluster}}    generator's parameter
    spec:
      project: my-project
      source:
        repoURL: https://github.com/infra-team/cluster-deployments.git
        targetRevision: HEAD
        path: guestbook/{{.cluster}}
      destination:
        server: '{{.url}}'      # {{.url}}    generator's parameter
        namespace: guestbook